name: taskvault
description: "TaskVault — Personal Task & Productivity Manager (offline-first, encrypted local storage)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Local persistent storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Secure key storage for Hive encryption key
  flutter_secure_storage: ^9.2.2

  # State management
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
